image: node:alpine

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install_mobile:
  stage: install
  script:
    - npm cache clean --force
    - npm install

jest-tests:
  stage: test
  script:
    - npm run test

eslint-test:
    stage: test
    script:
        npm run lint-fix
