image: node:alpine

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install_mobile:
  stage: install
  only:
    - develop
    - master
  script:
    - npm cache clean --force
    - npm install

jest-tests:
  stage: test
  script:
    - npm test

eslint-test:
    stage: test
    script:
        npm run lint
