import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e5eaeb',
  },
  header: {
    backgroundColor: '#5d9683',
    height: '15%',
  },
  body: {
    backgroundColor: '#e0dede',
    padding: '3%',
    flex: 1,
  },
  searchBar: {
    height: '35%',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    marginTop: '2%',
    marginLeft: '4%',
    marginRight: '4%',
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: '#eae5e5',
    borderColor: '#eae5e5',
  },
  searchInput: {
    marginRight: '4%',
  },
  filtersBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  filterButton: {
    marginTop: '4%',
    justifyContent: 'center',
    alignItems: 'center',
    width: '25%',
    borderRadius: 12,
    borderWidth: 1.2,
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 4,
    borderColor: 'white',
    position: 'absolute',
    alignSelf: 'center',
  },
  name: {
    fontSize: 22,
    color: '#000000',
    fontWeight: '600',
    marginTop: '45%',
    marginBottom: '5%',
  },
  buttonContainer: {
    height: '13%',
    marginTop: '4%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40%',
    borderRadius: 40,
    backgroundColor: '#335382',
  },
  buttonText: {
    color: 'white',
    alignItems: 'center',
    textAlign: 'center',
    margin: '4%',
    borderColor: '#ffffff',
    borderRadius: 8,
  },
  toolbarButton: {
    color: 'white',
    alignItems: 'center',
  },
  memoButton: {
    margin: '1%',
    padding: '2%',
    height: '80%',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#5d9683',
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
  },
  memoIcon: {
    alignSelf: 'center',
    width: '10%',
    height: '60%',
    marginRight: '2%',
  },
  memoItem: {
    margin: '1%',
    marginTop: '2%',
    padding: '2%',
    borderRadius: 20,
    borderWidth: 0.8,
    borderColor: '#585858',
    backgroundColor: 'white',
  },
  memoTitle: {
    margin: '1%',
    marginLeft: '2%',
    fontSize: 20,
    fontWeight: 'bold',
  },
  memoText: {
    margin: '2%',
    fontSize: 15,
  },
  memoTag: {
    margin: '2%',
    padding: '1%',
    justifyContent: 'center',
    alignItems: 'center',
    width: '22%',
    borderRadius: 12,
  },
  memoDelete: {
    marginTop: '2%',
    width: '15%',
    height: '50%',
  },
  infoBox: {
    paddingTop: '1%',
    marginBottom: '2%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '60%',
    borderRadius: 30,
    borderWidth: 0.6,
    borderColor: '#585858',
  },
  infoBoxEdit: {
    paddingTop: '1%',
    marginBottom: '2%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '70%',
    borderRadius: 30,
    borderWidth: 0.6,
    borderColor: '#585858',
  },
  infoContainer: {
    width: '85%',
    height: '12%',
    marginBottom: '5%',
    borderColor: '#2e548c',
    borderRadius: 40,
    textAlign: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoContainerNames: {
    width: '70%',
    height: '12%',
    borderColor: '#2e548c',
    backgroundColor: '#FFFFFF',
    borderRadius: 40,
    marginBottom: '5%',
    paddingLeft: '1%',
    marginLeft: '1%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  info: {
    marginLeft: '3%',
    marginRight: '8%',
  },
  infoIcon: {
    alignSelf: 'center',
    width: '10%',
    height: '40%',
    marginRight: '2%',
  },
  putEditIcon: {
    paddingTop: '35%',
    paddingLeft: '20%',
    alignItems: 'center',
  },
  infoIconEditPhoto: {
    paddingTop: '4%',
    paddingBottom: '1%',
    paddingLeft: '3%',
    paddingRight: '3%',
    marginBottom: '5%',
    backgroundColor: '#e5eaeb',
    alignItems: 'center',
    textAlign: 'center',
    borderWidth: 4,
    borderColor: 'white',
  },
  input: {
    fontSize: 12,
    color: '#000000',
    height: '55%',
    alignSelf: 'stretch',
    paddingLeft: '1%',
    paddingRight: '1%',
    borderColor: '#5b5b5b',
    borderBottomWidth: 1,
  },
  title_section: {
    fontSize: 12,
    color: '#696969',
    marginTop: '3%',
  },
  picker: {
    height: 30,
    width: 150,
  },
  modal: {
    backgroundColor: 'white',
    padding: '1%',
    marginTop: '14%',
    width: '95%',
    height: '88%',
    alignSelf: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#444544',
  },
  modalView: {
    alignItems: 'center',
    marginTop: '4%',
    marginBottom: '2%',
  },
  modalInputContainer: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderColor: 'grey',
    borderRadius: 5,
    borderWidth: 1,
    marginTop: '2%',
  },
  modalInput: {
    fontSize: 12,
    color: '#000000',
    marginLeft: '2%',
    marginRight: '2%',
  },
  modalButton: {
    width: '30%',
    backgroundColor: '#5d9683',
    borderColor: '#5d9683',
    borderRadius: 12,
    marginBottom: '2%',
  },
});

export default style;
