import {StyleSheet} from "react-native";

export const stylesPortrait = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#e5eaeb',
    },
    header: {
        backgroundColor: "#2e548c",
        height: '15%',
    },
    body:{
        backgroundColor: '#d7d7d7',
        padding: '4%',
        flex: 1,
    },
    searchBar: {
        height: '35%',
        justifyContent: 'flex-start',
        flexDirection: "row",
        marginTop: '2%',
        marginLeft: '4%',
        marginRight: '4%',
        borderRadius: 30,
        borderWidth: 1,
        backgroundColor: '#eae5e5',
        borderColor: '#eae5e5',
    },
    searchInput: {
        marginRight: '4%',
    },
    filtersBar: {
        flexDirection: "row",
        justifyContent: "space-around"
    },
    filterButton: {
        marginTop: '4%',
        justifyContent: 'center',
        alignItems: 'center',
        width: '25%',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'white'
    },
    avatar: {
        width: 150,
        height: 150,
        borderRadius: 75,
        borderWidth: 4,
        borderColor: "white",
        position: 'absolute',
        alignSelf:'center',
    },
    name:{
        fontSize:22,
        color:"#000000",
        fontWeight:'600',
        marginTop: '45%',
        marginBottom: '5%'
    },
    buttonContainer: {
        height: '13%',
        marginTop: '4%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '40%',
        borderRadius:40,
        backgroundColor: "#335382",
    },
    buttonText: {
        color: 'white',
        alignItems: 'center',
        textAlign:'center',
        margin: '4%',
        borderColor: '#ffffff',
        borderRadius:8,
    },
    toolbarButton: {
        color:'white',
        alignItems: 'center'
    },
    memoButton: {
        margin: "1%",
        padding: '2%',
        height: '80%',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'rgba(46,84,140,0.86)',
        backgroundColor: 'white',
        flexDirection: 'row',
        alignItems: 'center',
    },
    memoIcon: {
        alignSelf: 'center',
        width: '10%',
        height: '60%',
        marginRight: '2%'
    },
    memoItem: {
        margin: "1%",
        padding: '2%',
        height: '25%',
        borderRadius: 35,
        borderWidth: 1,
        borderColor: 'rgba(46,84,140,0.86)',
        backgroundColor: 'white',
    },
    memoTitle: {
        margin: '2%',
        fontSize:20,
    },
    memoText: {
        margin: '2%',
        fontSize:15,
    },
    memoTag: {
        margin: '2%',
        justifyContent: 'center',
        alignItems: 'center',
        width: '20%',
        borderRadius: 30,
        borderWidth: 1.5,
    },
    infoBox:{
        paddingTop: '1%',
        marginBottom: '2%',
        backgroundColor:'white',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '60%',
        borderRadius: 40,
        borderColor: '#bbc0c1',
    },
    infoBoxEdit:{
        paddingTop: '1%',
        marginBottom: '2%',
        backgroundColor:'white',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '70%',
        borderRadius: 40,
        borderColor: '#bbc0c1',
    },
    infoContainer: {
        width: '85%',
        height: '12%',
        marginBottom: '5%',
        borderColor: '#2e548c',
        borderRadius: 40,
        textAlign: 'center',
        flexDirection: 'row',
        alignItems:'center',
    },
    infoContainerNames: {
        width: '70%',
        height: '12%',
        borderColor: '#2e548c',
        backgroundColor: '#FFFFFF',
        borderRadius: 40,
        marginBottom: '5%',
        paddingLeft: '1%',
        marginLeft: '1%',
        flexDirection: 'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    info: {
        marginLeft:'3%',
        marginRight:'8%',
    },
    infoIcon:{
        alignSelf: 'center',
        width: '10%',
        height: '40%',
        marginRight: '2%'
    },
    putEditIcon: {
        paddingTop: '35%',
        paddingLeft: '20%',
        alignItems: 'center',
    },
    infoIconEditPhoto: {
        paddingTop: '4%',
        paddingBottom: '1%',
        paddingLeft: '3%',
        paddingRight: '3%',
        marginBottom: '5%',
        backgroundColor: '#e5eaeb',
        alignItems: 'center',
        textAlign: 'center',
        borderWidth: 4,
        borderColor: "white",
    },
    input: {
        fontSize: 12,
        color: '#000000',
        height: '55%',
        alignSelf: 'stretch',
        paddingLeft: '1%',
        paddingRight: '1%',
        borderColor: '#5b5b5b',
        borderBottomWidth: 1
    },
    title_section:{
        fontSize:12,
        color: "#696969",
        marginTop:'3%',
    },
});

export const stylesLandscape = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#e5eaeb',
    },
    header: {
        backgroundColor: "#2e548c",
        height: '25%',
    },
    body:{
        backgroundColor: '#e5eaeb',
        marginTop: "1%",
        alignItems: 'center',
        borderColor: '#bbc0c1',
        borderWidth: 0.2,
    },
    searchBar: {
        height: '35%',
        justifyContent: 'flex-start',
        flexDirection: "row",
        marginTop: '2%',
        marginLeft: '4%',
        marginRight: '4%',
        borderRadius: 30,
        borderWidth: 1,
        backgroundColor: '#eae5e5',
        borderColor: '#eae5e5',
    },
    searchInput: {
        marginRight: '4%',
    },
    filtersBar: {
        flexDirection: "row",
        justifyContent: "space-around"
    },
    filterButton: {
        marginTop: '4%',
        justifyContent: 'center',
        alignItems: 'center',
        width: '25%',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'white'
    },
    avatar: {
        width: 130,
        height: 130,
        borderRadius: 63,
        borderWidth: 4,
        borderColor: "white",
        alignSelf:'center',
        position: 'absolute',
    },
    name:{
        fontSize:22,
        color:"#000000",
        fontWeight:'600',
        marginTop: '16%',
        marginBottom: '1%'
    },
    buttonContainer: {
        height: '10%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '35%',
        borderRadius: 40,
        backgroundColor: "#2e548c",
    },
    buttonText: {
        color: 'white',
        fontWeight: 'bold',
        alignItems: 'center',
        textAlign:'center',
        margin: '1%',
        borderColor: '#ffffff',
        borderRadius:8,
        borderWidth: 1,
    },
    memoButton: {
        margin: "1%",
        padding: '2%',
        height: '80%',
        borderRadius: 30,
        borderWidth: 1,
        borderColor: 'rgba(46,84,140,0.86)',
        backgroundColor: 'white',
        flexDirection: 'row',
        alignItems: 'center',
    },
    memoIcon: {
        alignSelf: 'center',
        width: '10%',
        height: '60%',
        marginRight: '2%'
    },
    memoItem: {
        margin: "1%",
        padding: '2%',
        height: '32%',
        borderRadius: 35,
        borderWidth: 1,
        borderColor: 'rgba(46,84,140,0.86)',
        backgroundColor: 'white',
    },
    memoTitle: {
        margin: '2%',
        fontSize:20,
    },
    memoText: {
        margin: '2%',
        fontSize:15,
    },
    memoTag: {
        margin: '2%',
        justifyContent: 'center',
        alignItems: 'center',
        width: '20%',
        borderRadius: 30,
        borderWidth: 1.5,
    },
    toolbarButton:{
        color:'white',
        alignItems: 'center'
    },
    infoBox:{
        marginBottom: '3%',
        backgroundColor:'white',
        alignItems: 'center',
        justifyContent: 'center',
        width: '70%',
        height: '60%',
        borderRadius: 40,
        borderColor: '#bbc0c1',
    },
    infoBoxEdit:{
        marginBottom: '3%',
        backgroundColor:'white',
        alignItems: 'center',
        justifyContent: 'center',
        width: '70%',
        height: '60%',
        borderRadius: 40,
        borderColor: '#bbc0c1',
    },
    infoContainer: {
        width: '85%',
        height: '15%',
        borderColor: '#2e548c',
        backgroundColor: '#FFFFFF',
        borderRadius: 40,
        marginBottom: '0.5%',
        flexDirection: 'row',
        alignItems:'center',
    },
    infoContainerNames: {
        width: '70%',
        height: '9%',
        borderColor: '#2e548c',
        backgroundColor: '#FFFFFF',
        borderRadius: 40,
        marginBottom: '0.5%',
        marginLeft: '6%',
        flexDirection: 'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    info: {
        height: '40%',
        marginRight:'1%',
        marginLeft:'5%',
    },
    infoIcon:{
        width: '10%',
        height: '40%',
        marginLeft: '3%',
        marginRight: '3%',
    },
    putEditIcon: {
        paddingTop: '12%',
        paddingLeft: '12%',
        alignItems: 'center'
    },
    infoIconEditPhoto: {
        paddingTop: '1.5%',
        paddingBottom: '1%',
        paddingLeft: '1.5%',
        paddingRight: '1.5%',
        backgroundColor: '#e5eaeb',
        alignItems: 'center',
        textAlign: 'center',
        borderWidth: 4,
        borderColor: "white",
    },
    input: {
        fontSize: 12,
        color: '#000000',
        height: '45%',
        alignSelf: 'stretch',
        paddingLeft: '1%',
        paddingRight: '1%',
        borderColor: '#5b5b5b',
        borderBottomWidth: 1
    },
    title_section:{
        fontSize:12,
        color: "#696969",
        marginTop:'3%',
    },
});